name: Carina Automation Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  setup-jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
        id: setup-java
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

  maven-build:
    runs-on: ubuntu-latest
    needs: setup-jdk
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven Clean and Compile
        run: mvn -B clean validate compile --file pom.xml
        env:
          JAVA_HOME: ${{ needs.setup-jdk.outputs.java-home }}

  run-api-automation:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v3
      - name: Web Automation with Maven
        run: mvn -B test -Papi --file pom.xml
        env:
          JAVA_HOME: ${{ needs.setup-jdk.outputs.java-home }}

  run-web-automation:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v3
      - name: Run Selenium Server
        run: nohup java -jar $SELENIUM_JAR_PATH standalone &
      - name: Web Automation with Maven
        run: mvn -B test -Pweb --file pom.xml
        env:
          JAVA_HOME: ${{ needs.setup-jdk.outputs.java-home }}

  run-android-automation:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
          appium &
      - name: Run Appium Android Emulator and Tests
        env:
          JAVA_HOME: ${{ needs.setup-jdk.outputs.java-home }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          avd-name: Pixel_3_API_28
          api-level: 28
          script: mvn -B test -Pmobile --file pom.xml