name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  setup-jdk:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
        id: setup-java
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

  run-api-automation:
    runs-on: macos-latest
    needs: setup-jdk
    steps:
      - uses: actions/checkout@v3
      - name: Web Automation with Maven
        run: mvn -B validate test -Papi --file pom.xml
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

  run-web-automation:
    runs-on: ubuntu-latest
    needs: run-api-automation
    steps:
      - uses: actions/checkout@v3
      - name: Run Selenium Server
        run: nohup java -jar $SELENIUM_JAR_PATH standalone &
      - name: Web Automation with Maven
        run: mvn -B validate test -Pweb --file pom.xml
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

  run-android-automation:
    runs-on: macos-latest
    needs: run-web-automation
    steps:
      - uses: actions/checkout@v3
      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
          appium &
      - name: Run Appium Android Emulator and Tests
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          avd-name: Pixel_3_API_28
          api-level: 28
          script: mvn -B validate test -Pmobile --file pom.xml